# コンカレンシーはRAILS_MAX_THREADSと統一するようにする
# https://qiita.com/ts-3156/items/a5f8794a79148c9cfcbe
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:verbose: true
:concurrency: 5
:queues:
  - default
  - mailers
  - low
:schedule:
  # cron_test:
  #   cron: '0 * * * * *'   # Runs once per minute
  #   class: CronTestJob
  daily_check:
    # 7:00 だと LineMessageJob と被るので30 秒遅らせる
    cron: '30 0 7 * * *'
    class: DailyCheckJob
  send_line_daily_schedule:
    cron: '0 0 7 * * *'
    class: SendLineDailyScheduleJob
  sync_google_calendar_schedule:
    cron: '0 0 1 * * *'
    class: SyncGoogleCalendarSchedulesJob
