# コンカレンシーはRAILS_MAX_THREADSと統一するようにする
# https://qiita.com/ts-3156/items/a5f8794a79148c9cfcbe
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:concurrency: 5
:queues:
  - default
  - mailers
